#!/bin/bash
# Source this to load the full environment that hutch python uses

# edit this line only
export CONDA_ENVNAME="pcds-5.1.1"
#export CONDA_ENVNAME="dev"
export CONDA_BASE="/reg/g/pcds/pyps/conda/py39"
export HUTCH="mec"

unset PYTHONPATH
unset LD_LIBRARY_PATH

source "${CONDA_BASE}/etc/profile.d/conda.sh"
conda activate "${CONDA_ENVNAME}"
HERE=`dirname $(readlink -f $0)`
export PYTHONPATH="${HERE}:${HERE}/dev/devpath:${HERE}/../common/dev/devpath:${HERE}/mec/macros"
# PCDS 4.1.5 and the dev installation directory are incompatible:
# export PYTHONPATH="${HERE}:${HERE}/dev/devpath:/reg/g/pcds/pyps/apps/dev/pythonpath:${HERE}/../common/dev/devpath:${HERE}/mec/macros"
source pcdsdaq_lib_setup
export CONDA_PROMPT_MODIFIER="(${HUTCH}-${CONDA_ENVNAME})"
