#!/bin/bash
# Launch hutch-python with all devices
HERE=`dirname $(readlink -f $0)`
#source "${HERE}/mecversion"
source "${HERE}/mecenv"
#pathmunge "${CONDA_BIN}"
#source pcdsdaq_lib_setup
hutch-python --cfg "${HERE}/conf.yml" $@
